DbsPath:
  post:
    summary: Create a new database
    operationId: createDatabase
    tags:
      - database
    parameters:
      - name: dbName
        in: path
        required: true
        description: The name of the database
        schema:
          type: string
    responses:
      '200':
        $ref: 'components/responses.yaml#/SuccessResponse'
      '400':
        description: Invalid input
      '401':
        description: Authorization information is missing or invalid
      '500':
        description: Internal server error
      '550':
        description: Database is existed

  delete:
    summary: Delete a specific database
    operationId: deleteDatabase
    tags:
      - database
    parameters:
      - name: dbName
        in: path
        required: true
        description: The name of the database
        schema:
          type: string
    responses:
      '204':
        description: Database deleted successfully
      '400':
        description: Invalid input or bad request
      '401':
        description: Authorization information is missing or invalid
      '404':
        description: Database not found
      '500':
        description: Internal server error
      '562':
        description: Database not exist
  get:
    summary: Get vearch database
    operationId: getDb
    tags:
      - database
    parameters:
      - name: dbName
        in: path
        required: true
        description: The name of the database
        schema:
          type: string
    responses:
      '200':
        description: Database list successfully
      '400':
        description: Invalid input or bad request
      '401':
        description: Authorization information is missing or invalid
      '404':
        description: Database not found
      '500':
        description: Internal server error

Dbs:
  get:
    summary: List vearch database
    operationId: listDb
    tags:
      - database
    responses:
      '200':
        description: Database list successfully
      '400':
        description: Invalid input or bad request
      '401':
        description: Authorization information is missing or invalid
      '404':
        description: Database not found
      '500':
        description: Internal server error
